# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 180
    Tracing: Active
    DeadLetterQueue:
      Type: SNS
      TargetArn: arn:aws:sns:ap-northeast-1:267428311438:failed-lambda

Resources:
  Main:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/
      Handler: lambda_handler.default
      Environment:
        Variables:
          URL: dummy
          CHANNEL: dummy
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref Topic
  LogGroupMain:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Main}
      RetentionInDays: 14
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'slack-notification'

Outputs:
  SlackNotify:
    Description: "Lambda Function ARN"
    Value: !GetAtt Main.Arn
  SlackNotifyIamRole:
    Description: "Implicit IAM Role created for lambda function"
    Value: !GetAtt MainRole.Arn